# Generated by Django 3.1.7 on 2021-03-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_page404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page404',
            name='button_link',
        ),
    ]
