# Generated by Django 3.1.7 on 2021-03-16 16:25

import cms.home.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('link', cms.home.models.APIPageChooserBlock()), ('icon', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('content', wagtail.core.blocks.TextBlock(max_length=500, required=True))]))], blank=True, null=True),
        ),
    ]
