# Generated by Django 3.1.7 on 2021-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('home', '0014_auto_20210320_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountprofile',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='useraccountprofile',
            name='search_image',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.DeleteModel(
            name='UserAccountProfile',
        ),
    ]
