# Generated by Django 3.1.8 on 2021-05-12 09:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210320_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinpage',
            name='description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
