# Generated by Django 3.1.3 on 2020-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20201020_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='vimeo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='about_short_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='About short description'),
        ),
    ]
