# Generated by Django 3.1.3 on 2020-11-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20201130_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='header_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
