# Generated by Django 3.1.7 on 2021-03-02 20:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='blogtagindexpage',
            name='search_image',
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
