# Generated by Django 3.1.13 on 2021-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210910_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='district',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='province',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
    ]
