# Generated by Django 3.1.13 on 2021-09-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210910_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcode',
            options={'verbose_name_plural': 'Postcodes'},
        ),
    ]
