# Generated by Django 3.1.13 on 2021-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210803_2153'),
        ('products', '0002_auto_20210803_0701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationImage',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='location',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='OpeningHours',
        ),
        migrations.DeleteModel(
            name='RentObject',
        ),
    ]
