# Generated by Django 3.1.13 on 2021-08-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210803_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='location',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='google_photo_reference',
        ),
    ]
