# Generated by Django 3.1.13 on 2021-08-22 06:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210821_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
