# Generated by Django 3.1.13 on 2021-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210822_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('text', 'Text'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select'), ('textarea', 'Textarea')], max_length=150)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
