# Generated by Django 3.1.13 on 2021-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210905_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
