# Generated by Django 3.1.13 on 2021-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210905_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
