# Generated by Django 3.1.13 on 2021-09-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='street_number',
        ),
    ]
