# Generated by Django 3.1.13 on 2021-09-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210910_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
