# Generated by Django 3.1.13 on 2021-09-19 20:37

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_basics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to=products.models.ProductCategoryImage.update_filename)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='products.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
