# Generated by Django 3.1.13 on 2021-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productcategoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='long_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='short_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
