# Generated by Django 3.1.13 on 2021-09-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210925_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='day_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_ratings_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='utc_offset',
        ),
    ]
