# Generated by Django 3.1.4 on 2020-12-09 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cowork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='type',
            field=models.CharField(choices=[('phone', 'Phone'), ('desktop', 'Desktop'), ('meeting', 'Meeting')], max_length=150),
        ),
    ]
