# Generated by Django 3.1.4 on 2020-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0002_auto_20201209_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
