# Generated by Django 3.1.4 on 2020-12-28 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='cowork.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
