# Generated by Django 3.1.4 on 2020-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0005_auto_20201228_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
