# Generated by Django 3.1.4 on 2020-12-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0006_auto_20201228_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
