# Generated by Django 3.1.4 on 2020-12-28 18:17

import cowork.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0007_locationimage_is_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.FileField(upload_to=cowork.models.Image.update_filename),
        ),
    ]
