# Generated by Django 3.1.4 on 2020-12-29 22:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0008_auto_20201228_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_objects', to='cowork.location'),
        ),
    ]
