# Generated by Django 3.1.4 on 2021-01-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0017_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_intent_id',
        ),
    ]
