# Generated by Django 3.1.4 on 2021-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0018_remove_booking_payment_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
    ]
