# Generated by Django 3.1.4 on 2021-01-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0019_forwardingcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardingcontacts',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_contacts', to='cowork.location'),
        ),
    ]
