# Generated by Django 3.1.4 on 2021-01-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0020_forwardingcontacts_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForwardingContacts',
            new_name='ForwardingContact',
        ),
    ]
