# Generated by Django 3.1.4 on 2021-01-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0021_auto_20210111_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_bookings', to='cowork.rentobject'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rent_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_object_bookings', to='cowork.rentobject'),
        ),
    ]
