# Generated by Django 3.1.4 on 2021-01-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0023_auto_20210112_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='public_phone',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
