# Generated by Django 3.1.4 on 2021-01-16 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0025_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='cowork.location'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together=set(),
        ),
    ]
