# Generated by Django 3.1.5 on 2021-01-25 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0028_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='booking_type',
            field=models.CharField(choices=[('linking', 'Linking'), ('enquiry', 'Enquiry'), ('booking', 'Booking')], default='linking', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='cowork.country'),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='cowork.state'),
        ),
        migrations.AddField(
            model_name='location',
            name='street_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='utc_offset',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
