# Generated by Django 3.1.5 on 2021-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0029_auto_20210125_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
