# Generated by Django 3.1.5 on 2021-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0030_auto_20210125_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='air_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='coffee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='locker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='printer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='shower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
