# Generated by Django 3.1.5 on 2021-01-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0034_auto_20210127_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.AddField(
            model_name='location',
            name='business_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='formatted_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='formatted_phone_number',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='geometry',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='google_plus_code',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='google_reference',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hour_periods',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='reviews',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='user_ratings_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='vicinity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='locationimage',
            name='google_photo_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cityimage',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cowork.location'),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_states', to='cowork.country')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_locations', to='cowork.state'),
        ),
        migrations.AddField(
            model_name='province',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_provinces', to='cowork.state'),
        ),
    ]
