# Generated by Django 3.1.5 on 2021-02-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0035_auto_20210129_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='open_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='plotter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='relaxation_area',
            field=models.BooleanField(default=False),
        ),
    ]
