# Generated by Django 3.1.5 on 2021-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0036_auto_20210201_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
