# Generated by Django 3.1.5 on 2021-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0038_remove_district_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_meetingroom',
            field=models.BooleanField(default=False, verbose_name='meetingroom'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_onrequest',
            field=models.BooleanField(default=False, verbose_name='on request'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixdesk price (net)'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_print',
            field=models.BooleanField(default=False, verbose_name='print'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_scan',
            field=models.BooleanField(default=False, verbose_name='scan'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_storage',
            field=models.BooleanField(default=False, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_meetingroom',
            field=models.BooleanField(default=False, verbose_name='meetingroom'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_onrequest',
            field=models.BooleanField(default=False, verbose_name='on request'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk day-price (net)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_print',
            field=models.BooleanField(default=False, verbose_name='print'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_scan',
            field=models.BooleanField(default=False, verbose_name='scan'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_storage',
            field=models.BooleanField(default=False, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_meetingroom',
            field=models.BooleanField(default=False, verbose_name='meetingroom'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_onrequest',
            field=models.BooleanField(default=False, verbose_name='on request'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk hour-price (net)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_print',
            field=models.BooleanField(default=False, verbose_name='print'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_scan',
            field=models.BooleanField(default=False, verbose_name='scan'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_storage',
            field=models.BooleanField(default=False, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_meetingroom',
            field=models.BooleanField(default=False, verbose_name='meetingroom'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_onrequest',
            field=models.BooleanField(default=False, verbose_name='on request'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk price (net)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_print',
            field=models.BooleanField(default=False, verbose_name='print'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_scan',
            field=models.BooleanField(default=False, verbose_name='scan'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_storage',
            field=models.BooleanField(default=False, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AddField(
            model_name='location',
            name='meeting_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='meetingroom_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='meetingroom_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='virtual_office',
            field=models.BooleanField(default=False),
        ),
    ]
