# Generated by Django 3.1.5 on 2021-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0039_auto_20210202_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='google_plus_code',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_hour_periods',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='reviews',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
