# Generated by Django 3.1.5 on 2021-02-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0040_auto_20210202_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='open_24_7',
            new_name='access24_7',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='virtual_office',
            new_name='office_address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locker',
            new_name='storage',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_print',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_scan',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_day_print',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_day_scan',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_hour_print',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_hour_scan',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_month_print',
        ),
        migrations.RemoveField(
            model_name='location',
            name='flexdesk_month_scan',
        ),
        migrations.RemoveField(
            model_name='location',
            name='kitchen',
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_access24_7',
            field=models.BooleanField(default=False, verbose_name='access 24/7'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_coffee',
            field=models.BooleanField(default=False, verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='contract duration (month)'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='location',
            name='fixdesk_month_printer',
            field=models.BooleanField(default=False, verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_access24_7',
            field=models.BooleanField(default=False, verbose_name='access 24/7'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_coffee',
            field=models.BooleanField(default=False, verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='contract duration (month)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_day_printer',
            field=models.BooleanField(default=False, verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_access24_7',
            field=models.BooleanField(default=False, verbose_name='access 24/7'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_coffee',
            field=models.BooleanField(default=False, verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='contract duration (month)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_hour_printer',
            field=models.BooleanField(default=False, verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_access24_7',
            field=models.BooleanField(default=False, verbose_name='access 24/7'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_coffee',
            field=models.BooleanField(default=False, verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='contract duration (month)'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='location',
            name='flexdesk_month_printer',
            field=models.BooleanField(default=False, verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_access24_7',
            field=models.BooleanField(default=False, verbose_name='access 24/7'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_coffee',
            field=models.BooleanField(default=False, verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_contract_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='contract duration (month)'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_meetingroom',
            field=models.BooleanField(default=False, verbose_name='meetingroom'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_onrequest',
            field=models.BooleanField(default=False, verbose_name='on request'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_parking',
            field=models.BooleanField(default=False, verbose_name='parking'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Privatespace month-price (net)'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_printer',
            field=models.BooleanField(default=False, verbose_name='printer'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_storage',
            field=models.BooleanField(default=False, verbose_name='storage'),
        ),
        migrations.AddField(
            model_name='location',
            name='privatespace_month_wifi',
            field=models.BooleanField(default=False, verbose_name='wifi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixdesk month-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='flexdesk_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk month-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='flexdesk_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk month-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='flexdesk_month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Flexdesk month-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='meetingroom_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='meetingroom day-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='meetingroom_hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='meetingroom hour-price (net)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
