# Generated by Django 3.1.5 on 2021-02-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0042_auto_20210202_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
