# Generated by Django 3.1.5 on 2021-02-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0043_location_public_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_access24_7',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='access 24/7'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_coffee',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='coffee'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_meetingroom',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='meetingroom'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_office_address',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='office address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_onrequest',
            field=models.BooleanField(default=False, verbose_name='price on request'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_parking',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_printer',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='printer'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_storage',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='storage'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fixdesk_month_wifi',
            field=models.CharField(choices=[('excluded', 'Excluded'), ('included', 'Included'), ('upcharge', 'Upcharge')], default='excluded', max_length=10, verbose_name='wifi'),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_objects', to='cowork.location'),
        ),
    ]
