# Generated by Django 3.1.5 on 2021-02-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cowork', '0044_auto_20210206_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_access24_7',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_coffee',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_contract_duration',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_meetingroom',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_office_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_onrequest',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_parking',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_price',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_printer',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_storage',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fixdesk_month_wifi',
        ),
        migrations.AddField(
            model_name='location',
            name='preview_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_preview_image', to='cowork.locationimage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
