# Generated by Django 3.1.5 on 2021-02-10 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0045_auto_20210208_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_bookings', to='cowork.location'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rent_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_object_bookings', to='cowork.rentobject'),
        ),
    ]
