# Generated by Django 3.1.4 on 2021-01-10 18:04

from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cowork', '0017_city_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(blank=True, default=payments.models.increment_invoice_number, max_length=500, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cowork.booking')),
            ],
        ),
    ]
