# Generated by Django 3.1.13 on 2021-08-03 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_account', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=100)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='users',
            field=models.ManyToManyField(through='payments.PaymentAccountUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_no', models.CharField(blank=True, default=payments.models.increment_invoice_number, max_length=500, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.booking')),
            ],
        ),
    ]
