# Generated by Django 3.1.4 on 2021-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
