# Generated by Django 3.1.5 on 2021-02-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0046_auto_20210210_2145'),
        ('payments', '0003_auto_20210110_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cowork.booking'),
        ),
    ]
