# Generated by Django 3.1.7 on 2021-03-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20210210_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=100)),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='users',
            field=models.ManyToManyField(through='payments.PaymentAccountUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
