# Generated by Django 3.1.7 on 2021-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20210319_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentaccount',
            old_name='stripe',
            new_name='stripe_customer',
        ),
    ]
