# Generated by Django 3.1.13 on 2021-08-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='public_email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='public_phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='street_number',
        ),
    ]
