# Generated by Django 3.1.13 on 2021-10-01 15:34

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210820_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.Vendor.update_filename),
        ),
    ]
