# Generated by Django 3.1.13 on 2021-10-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='utc_offset',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_name',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
