# Generated by Django 3.1.13 on 2021-10-10 08:32

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211001_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.FileField(null=True, upload_to=profiles.models.Vendor.update_filename),
        ),
    ]
