# Generated by Django 3.1.7 on 2021-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountindexpage',
            name='cards',
        ),
        migrations.AddField(
            model_name='accountpage',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountpage',
            name='short_description',
            field=models.TextField(max_length=1055, null=True),
        ),
        migrations.AlterField(
            model_name='accountpage',
            name='description',
            field=models.TextField(max_length=1055, null=True),
        ),
    ]
