# Generated by Django 3.1.7 on 2021-04-01 17:33

import cms.user_account.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20210322_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountindexpage',
            name='cards',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('coming_soon', wagtail.core.blocks.BooleanBlock(default=False, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('link', cms.user_account.models.APIPageChooserBlock()), ('icon', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('content', wagtail.core.blocks.TextBlock(max_length=500, required=True))]))], blank=True, null=True),
        ),
    ]
