# Generated by Django 3.1.4 on 2020-12-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_short_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='About short description')),
                ('about_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='About address')),
                ('about_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='About phone')),
                ('about_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='About email')),
                ('header_cta_text', models.CharField(blank=True, max_length=500, null=True)),
                ('header_cta_link', models.URLField(blank=True, null=True)),
                ('header_cta_icon', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('vimeo_link', models.URLField(blank=True, null=True)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Theme',
            },
        ),
    ]
